USE cotopaxi;

DROP TABLE IF EXISTS cotopaxi.sociales_sintetico;

CREATE TABLE cotopaxi.sociales_sintetico (
  id INT NOT NULL PRIMARY KEY,
  row_id VARCHAR(16) NOT NULL UNIQUE,
  create_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  jefatura_femenina TINYINT NOT NULL,
  adultos_mayores   TINYINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO cotopaxi.sociales_sintetico (
  id, row_id, jefatura_femenina, adultos_mayores
)
SELECT
  n AS id,
  CONCAT('ROW-', LPAD(n, 6, '0')) AS row_id,
  CASE WHEN (CONV(SUBSTRING(MD5(CONCAT(n,'#JF')),1,16),16,10) / 0xFFFFFFFFFFFF) < 0.33 THEN 1 ELSE 0 END,
  CASE WHEN (CONV(SUBSTRING(MD5(CONCAT(n,'#AM')),1,16),16,10) / 0xFFFFFFFFFFFF) < 0.25 THEN 1 ELSE 0 END
FROM (
  SELECT (a.n + b.n*10 + c.n*100 + d.n*1000 + e.n*10000 + f.n*100000) + 1 AS n
  FROM (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
        UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
  CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
        UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
  CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
        UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c
  CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
        UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
  CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
        UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) e
  CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
        UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) f
) AS seq
WHERE n <= 135068;

COMMIT;
